[2025-02-02T07:08:41.921+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-02T07:08:41.959+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_dag.load_data_task manual__2025-02-02T07:08:24.170608+00:00 [queued]>
[2025-02-02T07:08:41.981+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_dag.load_data_task manual__2025-02-02T07:08:24.170608+00:00 [queued]>
[2025-02-02T07:08:41.982+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-02-02T07:08:42.012+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_task> on 2025-02-02 07:08:24.170608+00:00
[2025-02-02T07:08:42.030+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-02T07:08:42.033+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'load_data_task', 'manual__2025-02-02T07:08:24.170608+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/dagto_csv.py', '--cfg-path', '/tmp/tmp3quozpb1']
[2025-02-02T07:08:42.035+0000] {standard_task_runner.py:63} INFO - Started process 676 to run task
[2025-02-02T07:08:42.035+0000] {standard_task_runner.py:91} INFO - Job 215: Subtask load_data_task
[2025-02-02T07:08:42.135+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_dag.load_data_task manual__2025-02-02T07:08:24.170608+00:00 [running]> on host 2892ee60bb8a
[2025-02-02T07:08:42.307+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andres Urrea' AIRFLOW_CTX_DAG_ID='csv_dag' AIRFLOW_CTX_TASK_ID='load_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T07:08:24.170608+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-02T07:08:24.170608+00:00'
[2025-02-02T07:08:42.310+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-02T07:08:42.312+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-02T07:08:42.314+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dagto_csv.py", line 58, in save_to_df
    df = ti.xcom_pull(task_ids='df_all', key='df_all')
         ^^
NameError: name 'ti' is not defined
[2025-02-02T07:08:42.337+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_dag, task_id=load_data_task, execution_date=20250202T070824, start_date=20250202T070841, end_date=20250202T070842
[2025-02-02T07:08:42.365+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 215 for task load_data_task (name 'ti' is not defined; 676)
[2025-02-02T07:08:42.412+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-02T07:08:42.477+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T07:08:42.482+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
